spring:
  application:
    name: saasy-store-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:saasy_store}}
    username: ${DB_USERNAME:saasy_store}
    password: ${DB_PASSWORD:change-me}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URI:{baseUrl}/login/oauth2/code/{registrationId}}

app:
  security:
    admin-email: ${ADMIN_EMAIL}

server:
  error:
    include-binding-errors: never
    include-message: never
    include-stacktrace: never
